# Generated by Django 3.1.8 on 2021-11-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Descrição')),
                ('reference_code', models.IntegerField(verbose_name='Código de Referência')),
                ('internal_code', models.IntegerField(null=True, verbose_name='Código Interno')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='Imagem')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponivel')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
